/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicTestimoniRouteImport } from './routes/_public/testimoni'
import { Route as PublicPortofolioRouteImport } from './routes/_public/portofolio'
import { Route as PublicLayananRouteImport } from './routes/_public/layanan'
import { Route as PublicKontakRouteImport } from './routes/_public/kontak'
import { Route as PublicGhaziSportsHubRouteImport } from './routes/_public/ghazi-sports-hub'
import { Route as PublicAdinkoRouteImport } from './routes/_public/adinko'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ProtectedAdminPortfolioRouteImport } from './routes/_protected/admin/portfolio'
import { Route as ProtectedAdminLayananRouteImport } from './routes/_protected/admin/layanan'
import { Route as ProtectedAdminKontakRouteImport } from './routes/_protected/admin/kontak'
import { Route as ProtectedAdminKategoriRouteImport } from './routes/_protected/admin/kategori'
import { Route as ProtectedAdminIndexRouteImport } from './routes/_protected/admin/_index'
import { Route as ProtectedAdminPerusahaanNamaRouteImport } from './routes/_protected/admin/perusahaan.$nama'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTestimoniRoute = PublicTestimoniRouteImport.update({
  id: '/testimoni',
  path: '/testimoni',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPortofolioRoute = PublicPortofolioRouteImport.update({
  id: '/portofolio',
  path: '/portofolio',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLayananRoute = PublicLayananRouteImport.update({
  id: '/layanan',
  path: '/layanan',
  getParentRoute: () => PublicRoute,
} as any)
const PublicKontakRoute = PublicKontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => PublicRoute,
} as any)
const PublicGhaziSportsHubRoute = PublicGhaziSportsHubRouteImport.update({
  id: '/ghazi-sports-hub',
  path: '/ghazi-sports-hub',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAdinkoRoute = PublicAdinkoRouteImport.update({
  id: '/adinko',
  path: '/adinko',
  getParentRoute: () => PublicRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedAdminPortfolioRoute = ProtectedAdminPortfolioRouteImport.update({
  id: '/admin/portfolio',
  path: '/admin/portfolio',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminLayananRoute = ProtectedAdminLayananRouteImport.update({
  id: '/admin/layanan',
  path: '/admin/layanan',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminKontakRoute = ProtectedAdminKontakRouteImport.update({
  id: '/admin/kontak',
  path: '/admin/kontak',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminKategoriRoute = ProtectedAdminKategoriRouteImport.update({
  id: '/admin/kategori',
  path: '/admin/kategori',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminIndexRoute = ProtectedAdminIndexRouteImport.update({
  id: '/admin/_index',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminPerusahaanNamaRoute =
  ProtectedAdminPerusahaanNamaRouteImport.update({
    id: '/admin/perusahaan/$nama',
    path: '/admin/perusahaan/$nama',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/login': typeof AuthLoginRoute
  '/adinko': typeof PublicAdinkoRoute
  '/ghazi-sports-hub': typeof PublicGhaziSportsHubRoute
  '/kontak': typeof PublicKontakRoute
  '/layanan': typeof PublicLayananRoute
  '/portofolio': typeof PublicPortofolioRoute
  '/testimoni': typeof PublicTestimoniRoute
  '/admin': typeof ProtectedAdminIndexRoute
  '/admin/kategori': typeof ProtectedAdminKategoriRoute
  '/admin/kontak': typeof ProtectedAdminKontakRoute
  '/admin/layanan': typeof ProtectedAdminLayananRoute
  '/admin/portfolio': typeof ProtectedAdminPortfolioRoute
  '/admin/perusahaan/$nama': typeof ProtectedAdminPerusahaanNamaRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/login': typeof AuthLoginRoute
  '/adinko': typeof PublicAdinkoRoute
  '/ghazi-sports-hub': typeof PublicGhaziSportsHubRoute
  '/kontak': typeof PublicKontakRoute
  '/layanan': typeof PublicLayananRoute
  '/portofolio': typeof PublicPortofolioRoute
  '/testimoni': typeof PublicTestimoniRoute
  '/admin': typeof ProtectedAdminIndexRoute
  '/admin/kategori': typeof ProtectedAdminKategoriRoute
  '/admin/kontak': typeof ProtectedAdminKontakRoute
  '/admin/layanan': typeof ProtectedAdminLayananRoute
  '/admin/portfolio': typeof ProtectedAdminPortfolioRoute
  '/admin/perusahaan/$nama': typeof ProtectedAdminPerusahaanNamaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_public/adinko': typeof PublicAdinkoRoute
  '/_public/ghazi-sports-hub': typeof PublicGhaziSportsHubRoute
  '/_public/kontak': typeof PublicKontakRoute
  '/_public/layanan': typeof PublicLayananRoute
  '/_public/portofolio': typeof PublicPortofolioRoute
  '/_public/testimoni': typeof PublicTestimoniRoute
  '/_public/': typeof PublicIndexRoute
  '/_protected/admin/_index': typeof ProtectedAdminIndexRoute
  '/_protected/admin/kategori': typeof ProtectedAdminKategoriRoute
  '/_protected/admin/kontak': typeof ProtectedAdminKontakRoute
  '/_protected/admin/layanan': typeof ProtectedAdminLayananRoute
  '/_protected/admin/portfolio': typeof ProtectedAdminPortfolioRoute
  '/_protected/admin/perusahaan/$nama': typeof ProtectedAdminPerusahaanNamaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/adinko'
    | '/ghazi-sports-hub'
    | '/kontak'
    | '/layanan'
    | '/portofolio'
    | '/testimoni'
    | '/admin'
    | '/admin/kategori'
    | '/admin/kontak'
    | '/admin/layanan'
    | '/admin/portfolio'
    | '/admin/perusahaan/$nama'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/adinko'
    | '/ghazi-sports-hub'
    | '/kontak'
    | '/layanan'
    | '/portofolio'
    | '/testimoni'
    | '/admin'
    | '/admin/kategori'
    | '/admin/kontak'
    | '/admin/layanan'
    | '/admin/portfolio'
    | '/admin/perusahaan/$nama'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_public'
    | '/_auth/login'
    | '/_public/adinko'
    | '/_public/ghazi-sports-hub'
    | '/_public/kontak'
    | '/_public/layanan'
    | '/_public/portofolio'
    | '/_public/testimoni'
    | '/_public/'
    | '/_protected/admin/_index'
    | '/_protected/admin/kategori'
    | '/_protected/admin/kontak'
    | '/_protected/admin/layanan'
    | '/_protected/admin/portfolio'
    | '/_protected/admin/perusahaan/$nama'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/testimoni': {
      id: '/_public/testimoni'
      path: '/testimoni'
      fullPath: '/testimoni'
      preLoaderRoute: typeof PublicTestimoniRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/portofolio': {
      id: '/_public/portofolio'
      path: '/portofolio'
      fullPath: '/portofolio'
      preLoaderRoute: typeof PublicPortofolioRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/layanan': {
      id: '/_public/layanan'
      path: '/layanan'
      fullPath: '/layanan'
      preLoaderRoute: typeof PublicLayananRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/kontak': {
      id: '/_public/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof PublicKontakRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/ghazi-sports-hub': {
      id: '/_public/ghazi-sports-hub'
      path: '/ghazi-sports-hub'
      fullPath: '/ghazi-sports-hub'
      preLoaderRoute: typeof PublicGhaziSportsHubRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/adinko': {
      id: '/_public/adinko'
      path: '/adinko'
      fullPath: '/adinko'
      preLoaderRoute: typeof PublicAdinkoRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/admin/portfolio': {
      id: '/_protected/admin/portfolio'
      path: '/admin/portfolio'
      fullPath: '/admin/portfolio'
      preLoaderRoute: typeof ProtectedAdminPortfolioRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/layanan': {
      id: '/_protected/admin/layanan'
      path: '/admin/layanan'
      fullPath: '/admin/layanan'
      preLoaderRoute: typeof ProtectedAdminLayananRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/kontak': {
      id: '/_protected/admin/kontak'
      path: '/admin/kontak'
      fullPath: '/admin/kontak'
      preLoaderRoute: typeof ProtectedAdminKontakRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/kategori': {
      id: '/_protected/admin/kategori'
      path: '/admin/kategori'
      fullPath: '/admin/kategori'
      preLoaderRoute: typeof ProtectedAdminKategoriRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/_index': {
      id: '/_protected/admin/_index'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/perusahaan/$nama': {
      id: '/_protected/admin/perusahaan/$nama'
      path: '/admin/perusahaan/$nama'
      fullPath: '/admin/perusahaan/$nama'
      preLoaderRoute: typeof ProtectedAdminPerusahaanNamaRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAdminIndexRoute: typeof ProtectedAdminIndexRoute
  ProtectedAdminKategoriRoute: typeof ProtectedAdminKategoriRoute
  ProtectedAdminKontakRoute: typeof ProtectedAdminKontakRoute
  ProtectedAdminLayananRoute: typeof ProtectedAdminLayananRoute
  ProtectedAdminPortfolioRoute: typeof ProtectedAdminPortfolioRoute
  ProtectedAdminPerusahaanNamaRoute: typeof ProtectedAdminPerusahaanNamaRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminIndexRoute: ProtectedAdminIndexRoute,
  ProtectedAdminKategoriRoute: ProtectedAdminKategoriRoute,
  ProtectedAdminKontakRoute: ProtectedAdminKontakRoute,
  ProtectedAdminLayananRoute: ProtectedAdminLayananRoute,
  ProtectedAdminPortfolioRoute: ProtectedAdminPortfolioRoute,
  ProtectedAdminPerusahaanNamaRoute: ProtectedAdminPerusahaanNamaRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicRouteChildren {
  PublicAdinkoRoute: typeof PublicAdinkoRoute
  PublicGhaziSportsHubRoute: typeof PublicGhaziSportsHubRoute
  PublicKontakRoute: typeof PublicKontakRoute
  PublicLayananRoute: typeof PublicLayananRoute
  PublicPortofolioRoute: typeof PublicPortofolioRoute
  PublicTestimoniRoute: typeof PublicTestimoniRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAdinkoRoute: PublicAdinkoRoute,
  PublicGhaziSportsHubRoute: PublicGhaziSportsHubRoute,
  PublicKontakRoute: PublicKontakRoute,
  PublicLayananRoute: PublicLayananRoute,
  PublicPortofolioRoute: PublicPortofolioRoute,
  PublicTestimoniRoute: PublicTestimoniRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
