/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicTestimoniRouteImport } from './routes/_public/testimoni'
import { Route as PublicPortofolioRouteImport } from './routes/_public/portofolio'
import { Route as PublicLayananRouteImport } from './routes/_public/layanan'
import { Route as PublicKontakRouteImport } from './routes/_public/kontak'
import { Route as PublicGhaziSportsHubRouteImport } from './routes/_public/ghazi-sports-hub'
import { Route as PublicAdinkoRouteImport } from './routes/_public/adinko'
import { Route as Auth4928fnRouteImport } from './routes/_auth/4928fn'
import { Route as ProtectedKnbnw3PortfolioRouteImport } from './routes/_protected/knbnw3/portfolio'
import { Route as ProtectedKnbnw3LayananRouteImport } from './routes/_protected/knbnw3/layanan'
import { Route as ProtectedKnbnw3KontakRouteImport } from './routes/_protected/knbnw3/kontak'
import { Route as ProtectedKnbnw3KategoriRouteImport } from './routes/_protected/knbnw3/kategori'
import { Route as ProtectedKnbnw3IndexRouteImport } from './routes/_protected/knbnw3/_index'
import { Route as ProtectedKnbnw3PerusahaanNamaRouteImport } from './routes/_protected/knbnw3/perusahaan.$nama'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTestimoniRoute = PublicTestimoniRouteImport.update({
  id: '/testimoni',
  path: '/testimoni',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPortofolioRoute = PublicPortofolioRouteImport.update({
  id: '/portofolio',
  path: '/portofolio',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLayananRoute = PublicLayananRouteImport.update({
  id: '/layanan',
  path: '/layanan',
  getParentRoute: () => PublicRoute,
} as any)
const PublicKontakRoute = PublicKontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => PublicRoute,
} as any)
const PublicGhaziSportsHubRoute = PublicGhaziSportsHubRouteImport.update({
  id: '/ghazi-sports-hub',
  path: '/ghazi-sports-hub',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAdinkoRoute = PublicAdinkoRouteImport.update({
  id: '/adinko',
  path: '/adinko',
  getParentRoute: () => PublicRoute,
} as any)
const Auth4928fnRoute = Auth4928fnRouteImport.update({
  id: '/4928fn',
  path: '/4928fn',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedKnbnw3PortfolioRoute =
  ProtectedKnbnw3PortfolioRouteImport.update({
    id: '/knbnw3/portfolio',
    path: '/knbnw3/portfolio',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedKnbnw3LayananRoute = ProtectedKnbnw3LayananRouteImport.update({
  id: '/knbnw3/layanan',
  path: '/knbnw3/layanan',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedKnbnw3KontakRoute = ProtectedKnbnw3KontakRouteImport.update({
  id: '/knbnw3/kontak',
  path: '/knbnw3/kontak',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedKnbnw3KategoriRoute = ProtectedKnbnw3KategoriRouteImport.update({
  id: '/knbnw3/kategori',
  path: '/knbnw3/kategori',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedKnbnw3IndexRoute = ProtectedKnbnw3IndexRouteImport.update({
  id: '/knbnw3/_index',
  path: '/knbnw3',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedKnbnw3PerusahaanNamaRoute =
  ProtectedKnbnw3PerusahaanNamaRouteImport.update({
    id: '/knbnw3/perusahaan/$nama',
    path: '/knbnw3/perusahaan/$nama',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/4928fn': typeof Auth4928fnRoute
  '/adinko': typeof PublicAdinkoRoute
  '/ghazi-sports-hub': typeof PublicGhaziSportsHubRoute
  '/kontak': typeof PublicKontakRoute
  '/layanan': typeof PublicLayananRoute
  '/portofolio': typeof PublicPortofolioRoute
  '/testimoni': typeof PublicTestimoniRoute
  '/knbnw3': typeof ProtectedKnbnw3IndexRoute
  '/knbnw3/kategori': typeof ProtectedKnbnw3KategoriRoute
  '/knbnw3/kontak': typeof ProtectedKnbnw3KontakRoute
  '/knbnw3/layanan': typeof ProtectedKnbnw3LayananRoute
  '/knbnw3/portfolio': typeof ProtectedKnbnw3PortfolioRoute
  '/knbnw3/perusahaan/$nama': typeof ProtectedKnbnw3PerusahaanNamaRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/4928fn': typeof Auth4928fnRoute
  '/adinko': typeof PublicAdinkoRoute
  '/ghazi-sports-hub': typeof PublicGhaziSportsHubRoute
  '/kontak': typeof PublicKontakRoute
  '/layanan': typeof PublicLayananRoute
  '/portofolio': typeof PublicPortofolioRoute
  '/testimoni': typeof PublicTestimoniRoute
  '/knbnw3': typeof ProtectedKnbnw3IndexRoute
  '/knbnw3/kategori': typeof ProtectedKnbnw3KategoriRoute
  '/knbnw3/kontak': typeof ProtectedKnbnw3KontakRoute
  '/knbnw3/layanan': typeof ProtectedKnbnw3LayananRoute
  '/knbnw3/portfolio': typeof ProtectedKnbnw3PortfolioRoute
  '/knbnw3/perusahaan/$nama': typeof ProtectedKnbnw3PerusahaanNamaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_auth/4928fn': typeof Auth4928fnRoute
  '/_public/adinko': typeof PublicAdinkoRoute
  '/_public/ghazi-sports-hub': typeof PublicGhaziSportsHubRoute
  '/_public/kontak': typeof PublicKontakRoute
  '/_public/layanan': typeof PublicLayananRoute
  '/_public/portofolio': typeof PublicPortofolioRoute
  '/_public/testimoni': typeof PublicTestimoniRoute
  '/_public/': typeof PublicIndexRoute
  '/_protected/knbnw3/_index': typeof ProtectedKnbnw3IndexRoute
  '/_protected/knbnw3/kategori': typeof ProtectedKnbnw3KategoriRoute
  '/_protected/knbnw3/kontak': typeof ProtectedKnbnw3KontakRoute
  '/_protected/knbnw3/layanan': typeof ProtectedKnbnw3LayananRoute
  '/_protected/knbnw3/portfolio': typeof ProtectedKnbnw3PortfolioRoute
  '/_protected/knbnw3/perusahaan/$nama': typeof ProtectedKnbnw3PerusahaanNamaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/4928fn'
    | '/adinko'
    | '/ghazi-sports-hub'
    | '/kontak'
    | '/layanan'
    | '/portofolio'
    | '/testimoni'
    | '/knbnw3'
    | '/knbnw3/kategori'
    | '/knbnw3/kontak'
    | '/knbnw3/layanan'
    | '/knbnw3/portfolio'
    | '/knbnw3/perusahaan/$nama'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/4928fn'
    | '/adinko'
    | '/ghazi-sports-hub'
    | '/kontak'
    | '/layanan'
    | '/portofolio'
    | '/testimoni'
    | '/knbnw3'
    | '/knbnw3/kategori'
    | '/knbnw3/kontak'
    | '/knbnw3/layanan'
    | '/knbnw3/portfolio'
    | '/knbnw3/perusahaan/$nama'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_public'
    | '/_auth/4928fn'
    | '/_public/adinko'
    | '/_public/ghazi-sports-hub'
    | '/_public/kontak'
    | '/_public/layanan'
    | '/_public/portofolio'
    | '/_public/testimoni'
    | '/_public/'
    | '/_protected/knbnw3/_index'
    | '/_protected/knbnw3/kategori'
    | '/_protected/knbnw3/kontak'
    | '/_protected/knbnw3/layanan'
    | '/_protected/knbnw3/portfolio'
    | '/_protected/knbnw3/perusahaan/$nama'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/testimoni': {
      id: '/_public/testimoni'
      path: '/testimoni'
      fullPath: '/testimoni'
      preLoaderRoute: typeof PublicTestimoniRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/portofolio': {
      id: '/_public/portofolio'
      path: '/portofolio'
      fullPath: '/portofolio'
      preLoaderRoute: typeof PublicPortofolioRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/layanan': {
      id: '/_public/layanan'
      path: '/layanan'
      fullPath: '/layanan'
      preLoaderRoute: typeof PublicLayananRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/kontak': {
      id: '/_public/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof PublicKontakRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/ghazi-sports-hub': {
      id: '/_public/ghazi-sports-hub'
      path: '/ghazi-sports-hub'
      fullPath: '/ghazi-sports-hub'
      preLoaderRoute: typeof PublicGhaziSportsHubRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/adinko': {
      id: '/_public/adinko'
      path: '/adinko'
      fullPath: '/adinko'
      preLoaderRoute: typeof PublicAdinkoRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/4928fn': {
      id: '/_auth/4928fn'
      path: '/4928fn'
      fullPath: '/4928fn'
      preLoaderRoute: typeof Auth4928fnRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/knbnw3/portfolio': {
      id: '/_protected/knbnw3/portfolio'
      path: '/knbnw3/portfolio'
      fullPath: '/knbnw3/portfolio'
      preLoaderRoute: typeof ProtectedKnbnw3PortfolioRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/knbnw3/layanan': {
      id: '/_protected/knbnw3/layanan'
      path: '/knbnw3/layanan'
      fullPath: '/knbnw3/layanan'
      preLoaderRoute: typeof ProtectedKnbnw3LayananRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/knbnw3/kontak': {
      id: '/_protected/knbnw3/kontak'
      path: '/knbnw3/kontak'
      fullPath: '/knbnw3/kontak'
      preLoaderRoute: typeof ProtectedKnbnw3KontakRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/knbnw3/kategori': {
      id: '/_protected/knbnw3/kategori'
      path: '/knbnw3/kategori'
      fullPath: '/knbnw3/kategori'
      preLoaderRoute: typeof ProtectedKnbnw3KategoriRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/knbnw3/_index': {
      id: '/_protected/knbnw3/_index'
      path: '/knbnw3'
      fullPath: '/knbnw3'
      preLoaderRoute: typeof ProtectedKnbnw3IndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/knbnw3/perusahaan/$nama': {
      id: '/_protected/knbnw3/perusahaan/$nama'
      path: '/knbnw3/perusahaan/$nama'
      fullPath: '/knbnw3/perusahaan/$nama'
      preLoaderRoute: typeof ProtectedKnbnw3PerusahaanNamaRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface AuthRouteChildren {
  Auth4928fnRoute: typeof Auth4928fnRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  Auth4928fnRoute: Auth4928fnRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedRouteChildren {
  ProtectedKnbnw3IndexRoute: typeof ProtectedKnbnw3IndexRoute
  ProtectedKnbnw3KategoriRoute: typeof ProtectedKnbnw3KategoriRoute
  ProtectedKnbnw3KontakRoute: typeof ProtectedKnbnw3KontakRoute
  ProtectedKnbnw3LayananRoute: typeof ProtectedKnbnw3LayananRoute
  ProtectedKnbnw3PortfolioRoute: typeof ProtectedKnbnw3PortfolioRoute
  ProtectedKnbnw3PerusahaanNamaRoute: typeof ProtectedKnbnw3PerusahaanNamaRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedKnbnw3IndexRoute: ProtectedKnbnw3IndexRoute,
  ProtectedKnbnw3KategoriRoute: ProtectedKnbnw3KategoriRoute,
  ProtectedKnbnw3KontakRoute: ProtectedKnbnw3KontakRoute,
  ProtectedKnbnw3LayananRoute: ProtectedKnbnw3LayananRoute,
  ProtectedKnbnw3PortfolioRoute: ProtectedKnbnw3PortfolioRoute,
  ProtectedKnbnw3PerusahaanNamaRoute: ProtectedKnbnw3PerusahaanNamaRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicRouteChildren {
  PublicAdinkoRoute: typeof PublicAdinkoRoute
  PublicGhaziSportsHubRoute: typeof PublicGhaziSportsHubRoute
  PublicKontakRoute: typeof PublicKontakRoute
  PublicLayananRoute: typeof PublicLayananRoute
  PublicPortofolioRoute: typeof PublicPortofolioRoute
  PublicTestimoniRoute: typeof PublicTestimoniRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAdinkoRoute: PublicAdinkoRoute,
  PublicGhaziSportsHubRoute: PublicGhaziSportsHubRoute,
  PublicKontakRoute: PublicKontakRoute,
  PublicLayananRoute: PublicLayananRoute,
  PublicPortofolioRoute: PublicPortofolioRoute,
  PublicTestimoniRoute: PublicTestimoniRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
